apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shopcar-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: shopcar.dev
      http:
        paths:
          - pathType: Prefix
            path: /customer(/|$)(.*)
            backend:
              service:
                name: ms-customer
                port:
                  number: 8080
          - pathType: Prefix
            path: /order(/|$)(.*)
            backend:
              service:
                name: ms-order
                port:
                  number: 8080
          - pathType: Prefix
            path: /vehicle(/|$)(.*)
            backend:
              service:
                name: ms-vehicle
                port:
                  number: 8080
