name: Deploy kubernetes extras to EKS

on:
  push:
    branches:
      - main
    paths:
      - '**'
      - '!README.md'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Obter credenciais do cluster EKS
        run: |
          aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME_PRD }} --region ${{ secrets.AWS_REGION }}

      - name: Aplicar manifests Ingress
        run: |
          kubectl apply -f kubernetes/ingress/ingress.yaml

      - name: Aplicar manifests Métrics
        run: |
          kubectl apply -f kubernetes/metrics/metrics.yaml
        
