name: Destroy Databases from EKS

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: "Tem certeza que deseja destruir a infraestrutura? Digite: sim"
        required: true
        default: "não"

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Obter credenciais do cluster EKS
        run: |
          aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME_PRD }} --region ${{ secrets.AWS_REGION }}

      - name: Remover manifests Ingress
        run: |
          kubectl delete -f kubernetes/ingress/ --ignore-not-found

      - name: Remover manifests Metrics
        run: |
          kubectl delete -f kubernetes/metrics/ --ignore-not-found
